@url = http://localhost:3100



GET {{url}}/version
###



POST {{url}}/newMatch
Content-Type: application/json

{
	"username": "pepito"
}
###



POST {{url}}/newMatch
Content-Type: application/json

{
	"username": "pepito",
	"matchId": "61fef092da23c159cc915a19"
}
###



GET {{url}}/match/61fef092da23c159cc915a19
###



PUT {{url}}/match
Content-Type: application/json

{
	"matchId": "61fc547e2029b06b54120145",
	"coords": [0, 0]
}
###



GET {{url}}/ranking
###



GET {{url}}/ranking/pepito
###
